apiVersion: v1
kind: Service
metadata:
  name: deployment
  namespace: namespace-workflow-1732802045123
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000